src/books/urls.py
from django.urls import path

from books import views as books_views

app_name = 'books'

urlpatterns = [

    path('book/<int:pk>/', books_views.BookDetailView.as_view(), name='book'),
    path('book-list/', books_views.BookListView.as_view(), name='book-list'),
    path('book-list-crew/', books_views.CrewBookListView.as_view(), name='book-list-crew'),
    path('home-books/', books_views.HomeBookListView.as_view(), name='home-books'),
    path('book_create/', books_views.BookCreateView.as_view(), name='book-create'),
    path('book_update/<int:pk>/', books_views.BookUpdateView.as_view(), name='book-update'),
    path('book_delete/<int:pk>/', books_views.BookDeleteView.as_view(), name='book-delete'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

from catalogs import views as catalogs_views
from books import views as books_views
#from books import urls, views as books_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('author/', include('catalogs.urls', namespace='author')),
    path('genre/', include('catalogs.urls', namespace='genre')),
    path('series/', include('catalogs.urls', namespace='series')),
    path('publishinghouse/', include('catalogs.urls', namespace='publishinghouse')),
    path('books/', include('books.urls', namespace='books')),
    path('accounts/', include('users.urls', namespace='accounts')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('comments/', include('comments.urls', namespace='comments')),

    path('', books_views.HomeBookListView.as_view(), name='home'),
    path('catalogs/', catalogs_views.CrewPage.as_view(), name='crew-page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users import views as users_views


app_name = 'users'

urlpatterns = [

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(redirect_field_name='home_books.html'), name='logout'), #система ищет нейки профайл!
    path('update-account/<int:pk>/', users_views.CustomerUpdateView.as_view(), name='update-account'),
    path('detail-account/<int:pk>/', users_views.CustomerDetailView.as_view(), name='detail-account'),

    path('register/', users_views.RegisterView.as_view(), name='register'),

    path('customer-list/', users_views.CustomerListView.as_view(), name='customer-list'),
 
    # path('create/', users_views.UserCreateView.as_view(), name='create'),
    # path('account/<int:pk>/', users_views.EmployeeDetailView.as_view(), name='account'),
    # path('account-list', users_views.EmployeeListView.as_view(), name='account-list'),


    # path('account/<str:user>', users_views.EmployeeDetailView.as_view(template_name='employee_detail.html'), name='account'),
    #path('create/', auth_views.CustomerCreateView.as_view()),
    #

]

src/templates/base.html
{% load static %}
{% load my_tags %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <title>{% block title %}Default title{% endblock title %}</title>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
                /* Custom page CSS
        -------------------------------------------------- */
        /* Not required for template or sticky footer method. */

        main > .container {
        padding: 60px 15px 0;
        }
      </style>
</head>
<body class="d-flex flex-column h-100">
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Best Books</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              {% include './top_menu.html' %}
              <form form action="{% url 'books:home-books' %}" class="d-flex">
                <input class="form-control me-2" type="text" name="q" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
      </header>
      <main class="flex-shrink-0">
        <div class="container">
          <br>
          {% if messages %}
           
                {% for message in messages %}
                <div class="alert alert-success" role="alert">
                  {{ message }}
                </div>
                {% endfor %}
           {% endif %}
         
    {% block body %}Default body{% endblock body %}
    </div>
    </main>

    <footer class="footer mt-auto py-3 bg-light">
      <div class="container">
        <span class="text-muted">Учебный проект. Евгений Кожушко. 2021</span>
        {% if user.is_staff or user.is_superuser %}
        <a href="{% url 'crew-page' %}">Для персонала</a>
        {% endif %}
      </div>
    </footer>
       
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  
    {% block custom_scripts %}{% endblock custom_scripts %}
</body>
</html>

src/templates/top_menu.html
{% load my_tags %}

<ul class="navbar-nav me-auto mb-2 mb-md-0">
    <li class="nav-item">
      {% if not user.is_active %}
      <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Войти</a>
    </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'accounts:register' %}">Зарегистрироваться</a>
    </li>
    {% if user.is_active %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'accounts:logout' %}" tabindex="-1" aria-disabled="true">Выход</a>
    </li>
    {% endif %}
    <li class="nav-item">
      {% if user.is_superuser %}
      <a class="nav-link" aria-current="page" href="/admin">Админка</a>
      {% endif %}
    </li>
    <li class="nav-item">
      {% if user.is_active %}
      <a class="nav-link " aria-current="page" href="{% url 'accounts:detail-account' user.customer.pk %}">Добро пожаловать на сайт, {{ user.customer }} !</a>
    </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Один доллар США к Белорусскому рублю {% currency_rate %} BYN</a>
    </li>
</ul>