src/books/urls.py
from django.urls import path

from books import views as books_views

app_name = 'books'

urlpatterns = [

    path('book/<int:pk>/', books_views.BookDetailView.as_view(), name='book'),
    path('book-list/', books_views.BookListView.as_view(), name='book-list'),
    path('book-list-crew/', books_views.CrewBookListView.as_view(), name='book-list-crew'),
    path('home-books/', books_views.HomeBookListView.as_view(), name='home-books'),
    path('book_create/', books_views.BookCreateView.as_view(), name='book-create'),
    path('book_update/<int:pk>/', books_views.BookUpdateView.as_view(), name='book-update'),
    path('book_delete/<int:pk>/', books_views.BookDeleteView.as_view(), name='book-delete'),
]

src/catalogs/urls.py
from django.urls import path

from catalogs import views as catalogs_views

app_name = 'catalogs'

urlpatterns = [
    path('author/<int:pk>/', catalogs_views.AuthorDetailView.as_view(),name='author'),
    path('author-list/', catalogs_views.AuthorListView.as_view(), name='author-list'),
    path('author_create/', catalogs_views.AuthorCreateView.as_view(), name='author-create'),
    path('author_update/<int:pk>/', catalogs_views.AuthorUpdateView.as_view(), name='author-update'),
    path('author_delete/<int:pk>/', catalogs_views.AuthorDeleteView.as_view(), name='author-delete'),

    path('series/<int:pk>/', catalogs_views.SeriesDetailView.as_view(), name='series'),
    path('series-list', catalogs_views.SeriesListView.as_view(), name='series-list'),
    path('series_create/', catalogs_views.SeriesCreateView.as_view(), name='series-create'),
    path('series_update/<int:pk>/', catalogs_views.SeriesUpdateView.as_view(), name='series-update'),
    path('series_delete/<int:pk>/', catalogs_views.SeriesDeleteView.as_view(), name='series-delete'),

    path('genre/<int:pk>/', catalogs_views.GenreDetailView.as_view(), name='genre'),
    path('genre-list/', catalogs_views.GenreListView.as_view(), name='genre-list'),
    path('genre_create/', catalogs_views.GenreCreateView.as_view(), name='genre-create'),
    path('genre_update/<int:pk>/', catalogs_views.GenreUpdateView.as_view(), name='genre-update'),
    path('genre_delete/<int:pk>/', catalogs_views.GenreDeleteView.as_view(), name='genre-delete'),

    path('published/<int:pk>/', catalogs_views.PublishingHouseDetailView.as_view(), name='published'),
    path('published-list/', catalogs_views.PublishingHouseListView.as_view(), name='published-list'),
    path('published_create/', catalogs_views.PublishingHouseCreateView.as_view(), name='published-create'),
    path('published_update/<int:pk>/', catalogs_views.PublishingHouseUpdateView.as_view(), name='published-update'),
    path('published_delete/<int:pk>/', catalogs_views.PublishingHouseDeleteView.as_view(), name='published-delete'),

]

src/orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.CreateOrderView.as_view(),name='create-order'),
    path('list-order/', views.ListOrderView.as_view(),name='list-order'),
    path('deteil-order/<int:pk>/', views.DetailOrderView.as_view(),name='deteil-order'),
    path('update-order/<int:pk>/', views.UpdateOrderView.as_view(),name='update-order'),
    path('customer-list-order/', views.CustomerOrderListView.as_view(),name='customer-list-order'),
    path('customer-order-update/<int:pk>/', views.CustomerUpdateOrderView.as_view(), name='customer-order-update'),
    # path('author_delete/<int:pk>/', cities_views.AuthorDeleteView.as_view(), name='author-delete'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

from catalogs import views as catalogs_views
from books import views as books_views
#from books import urls, views as books_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('author/', include('catalogs.urls', namespace='author')),
    path('genre/', include('catalogs.urls', namespace='genre')),
    path('series/', include('catalogs.urls', namespace='series')),
    path('publishinghouse/', include('catalogs.urls', namespace='publishinghouse')),
    path('books/', include('books.urls', namespace='books')),
    path('accounts/', include('users.urls', namespace='accounts')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('comments/', include('comments.urls', namespace='comments')),

    path('', books_views.HomeBookListView.as_view(), name='home'),
    path('catalogs/', catalogs_views.CrewPage.as_view(), name='crew-page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users import views as users_views


app_name = 'users'

urlpatterns = [

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(redirect_field_name='home_books.html'), name='logout'), #система ищет нейки профайл!
    path('update-account/<int:pk>/', users_views.CustomerUpdateView.as_view(), name='update-account'),
    path('detail-account/<int:pk>/', users_views.CustomerDetailView.as_view(), name='detail-account'),

    path('register/', users_views.RegisterView.as_view(), name='register'),

    path('customer-list/', users_views.CustomerListView.as_view(), name='customer-list'),
 
    # path('create/', users_views.UserCreateView.as_view(), name='create'),
    # path('account/<int:pk>/', users_views.EmployeeDetailView.as_view(), name='account'),
    # path('account-list', users_views.EmployeeListView.as_view(), name='account-list'),


    # path('account/<str:user>', users_views.EmployeeDetailView.as_view(template_name='employee_detail.html'), name='account'),
    #path('create/', auth_views.CustomerCreateView.as_view()),
    #

]

src/books/models.py
from django.db import models
from django.urls import reverse
from catalogs.models import Author, Genre, Series, PublishingHouse

# Create your models here.

class Book(models.Model):
    title_book = models.CharField(verbose_name="Название книги", max_length= 200)
    picture_book = models.ImageField(verbose_name="Картинка", upload_to = 'author/%Y/%m/%d/')
    book_price = models.IntegerField(verbose_name="Цена книги(BYN)")
    book_author = models.ManyToManyField(Author, related_name='authors') # должен быть справочник
    book_series = models.ForeignKey(Series, on_delete=models.PROTECT, related_name='series', blank=True, null=True) # должен быть справочник
    book_genre = models.ForeignKey(Genre, on_delete=models.PROTECT, related_name='genres') # должен быть справочник
    year_publishing = models.IntegerField(verbose_name= "Год издания")
    number_pages = models.IntegerField(verbose_name="Количество страниц")
    binding = models.CharField(verbose_name="Переплет",max_length= 100) # можно сделать справочик
    size = models.CharField(verbose_name="Формат", max_length= 100)
    ISBN = models.CharField(verbose_name="ISBN",max_length= 100)
    weight = models.IntegerField(verbose_name="Вес (гр)")
    age_restrictions = models.CharField(verbose_name="Возрастные ограничения",max_length=20)# можно сделать справочик
    publishing_house = models.ForeignKey(PublishingHouse, on_delete=models.PROTECT, related_name='publishing_houses') # должен быть справочник
    in_stock = models.IntegerField(verbose_name="Количество в наличии")
    available_to_order = models.BooleanField(verbose_name="Доступна к заказу", default=True)
    rating = models.IntegerField(verbose_name="Рейтинг (0-10)", blank=True, null=True)
    date_inclusion = models.DateTimeField(verbose_name="Дата внесения в каталог", auto_now_add=True, auto_now=False)
    date_change = models.DateTimeField(verbose_name="Дата последнего изменения карточки", auto_now_add=False, auto_now=True)

    def __str__(self) -> str:
        return f"{self.title_book}"

    def get_absolute_url(self):
        return reverse('books:book-list-crew')
    class Meta:
        verbose_name = "Книга"
        verbose_name_plural = "Книги"

src/catalogs/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Author(models.Model):
    dim_1 = models.CharField(verbose_name='Выбор автора', max_length=60)
    author_discription = models.TextField(verbose_name= 'Описание', blank=True, null=True)
    picture_author = models.ImageField(verbose_name="Картинка", upload_to = 'author/%Y/%m/%d/',blank=True, null=True)

    def __str__(self) -> str:
        return self.dim_1

    def get_absolute_url(self):
        return reverse('author:author-list')

    class Meta:
        verbose_name = "Выбор автора"
        verbose_name_plural = "Выбор автора"
class Series(models.Model):
    dim_2 = models.CharField(verbose_name='Выбор серии', max_length=60)
    series_discription = models.TextField(verbose_name= 'Описание', blank=True, null=True)

    def __str__(self) -> str:
        return self.dim_2

    def get_absolute_url(self):
        return reverse('series:series-list')
    class Meta:
        verbose_name = "Выбор серии"
        verbose_name_plural = "Выбор серии"   
class Genre(models.Model):
    dim_3 = models.CharField(verbose_name='Выбор жанра', max_length=60)
    genre_discription = models.TextField(verbose_name= 'Описание', blank=True, null=True)
    
    def __str__(self) -> str:
        return self.dim_3

    def get_absolute_url(self):
        return reverse('genre:genre-list')    
    class Meta:
        verbose_name = "Выбор жанра"
        verbose_name_plural = "Выбор жанра"        
class PublishingHouse(models.Model):
    dim_4 = models.CharField(verbose_name='Выбор издателя', max_length=60)
    publishing_house_discription = models.TextField(verbose_name= 'Описание', blank=True, null=True)
    
    def __str__(self) -> str:
        return self.dim_4

    def get_absolute_url(self):
        return reverse('publishinghouse:published-list')
    class Meta:
        verbose_name = "Выбор издателя"
        verbose_name_plural = "Выбор издателя"   

src/books/forms.py
from django import forms
from . import models

class CreateBookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = '__all__'       

src/catalogs/forms.py
from django import forms
from . import models

class CreateAuthorForm(forms.ModelForm):
    class Meta:
        model = models.Author
        fields = '__all__'

class CreateSeriesForm(forms.ModelForm):
    class Meta:
        model = models.Series
        fields = '__all__'

class CreateGenreForm(forms.ModelForm):
    class Meta:
        model = models.Genre
        fields = '__all__'

class CreatePublishingHouseForm(forms.ModelForm):
    class Meta:
        model = models.PublishingHouse
        fields = '__all__'    

src/books/views.py
from django.core import paginator
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db.models import Q
from django.core.paginator import Paginator

from . import models
from . import forms

# Create your views here.

class BookDetailView(DetailView):
    model = models.Book

class BookListView(ListView):
    model = models.Book
    paginate_by = 3

    def get_queryset(self):
        qs = super().get_queryset()
        filter = self.request.GET.get('filter')
        q = self.request.GET.get('q')
        print(q)
        if q:
            # qs.filter(title_book__icontains=q)
            qs = qs.filter(Q(title_book__icontains=q) | Q(book_author__dim_1__icontains=q))
        return qs


class CrewBookListView(ListView):
    model = models.Book
    template_name = 'books/crewbook_list.html'
    paginate_by = 10
    def get_queryset(self):
        qs = super().get_queryset()
        filter = self.request.GET.get('filter')
        q = self.request.GET.get('q')
        print(q)
        if q:
            # qs.filter(title_book__icontains=q)
            qs = qs.filter(Q(title_book__icontains=q) | Q(book_author__dim_1__icontains=q))
        return qs        

class HomeBookListView(ListView):
    model = models.Book
    template_name = 'books/home_books.html'
    paginate_by = 6
    def get_queryset(self):
        qs = super().get_queryset()
        filter = self.request.GET.get('filter')
        q = self.request.GET.get('q')
        print(q)
        if q:
            qs = qs.filter(Q(title_book__icontains=q) | Q(book_author__dim_1__icontains=q))
        return qs     


class BookCreateView(PermissionRequiredMixin, CreateView):
    model = models.Book
    form_class = forms.CreateBookForm
    login_url = 'accounts:login'
    permission_required = 'books.add_book'

class BookUpdateView(PermissionRequiredMixin, UpdateView):
    model = models.Book
    form_class = forms.CreateBookForm
    login_url = 'accounts:login'
    permission_required = 'books.change_book'
    
class BookDeleteView(PermissionRequiredMixin, DeleteView):
    model = models.Book
    success_url = reverse_lazy('books:book-list-crew') 
    login_url = 'accounts:login'
    permission_required = 'books.delete_book'

src/catalogs/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

from . import models
from . import forms

# Create your views here.

class Home(TemplateView):
    template_name = 'catalogs/home.html'

class CrewPage(TemplateView):
    template_name = 'catalogs/crew_page.html'
  
#Author
class AuthorDetailView(DetailView):
    model = models.Author

class AuthorListView(ListView):
    model = models.Author

class AuthorCreateView(CreateView):
    model = models.Author
    form_class = forms.CreateAuthorForm

class AuthorUpdateView(UpdateView):
    model = models.Author
    form_class = forms.CreateAuthorForm

class AuthorDeleteView(DeleteView):
    model = models.Author
    success_url = reverse_lazy('author:author-list')    

#Series
class SeriesDetailView(DetailView):
    model = models.Series

class SeriesListView(ListView):
    model = models.Series

class SeriesCreateView(CreateView):
    model = models.Series
    form_class = forms.CreateSeriesForm
    #fields = ('dim_2', 'series_discription')

class SeriesUpdateView(UpdateView):
    model = models.Series
    form_class = forms.CreateSeriesForm

class SeriesDeleteView(DeleteView):
    model = models.Series
    success_url = reverse_lazy('series:series-list')    

#Genre
class GenreDetailView(DetailView):
    model = models.Genre

class GenreListView(ListView):
    model = models.Genre    

class GenreCreateView(CreateView):
    model = models.Genre
    form_class = forms.CreateGenreForm

class GenreUpdateView(UpdateView):
    model = models.Genre
    form_class = forms.CreateGenreForm

class GenreDeleteView(DeleteView):
    model = models.Genre
    success_url = reverse_lazy('genre:genre-list') 

#Publishing House   
class PublishingHouseDetailView(DetailView):
    model = models.PublishingHouse

class PublishingHouseListView(ListView):
    model = models.PublishingHouse   

class PublishingHouseCreateView(CreateView):
    model = models.PublishingHouse
    form_class = forms.CreatePublishingHouseForm

class PublishingHouseUpdateView(UpdateView):
    model = models.PublishingHouse
    form_class = forms.CreatePublishingHouseForm

class PublishingHouseDeleteView(DeleteView):
    model = models.PublishingHouse
    success_url = reverse_lazy('publishinghouse:published-list')

src/catalogs/templates/catalogs/author_detail.html
{% extends 'base.html' %}
{% load template_tags %}
{% block title %}Detail author{% endblock title %}
{% block body %}
    <div class="card" style="width: 18rem;">
    <img src="{{ author.picture_author.url }}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Автор</h5>
      <p class="card-text">    {{ author }}<br>
        ID : {{ author.pk }} <br>
        Description : {{ author.author_discription }} <br></p>
      <a href="{% url 'author:author-list' %}" class="btn btn-primary">К списку</a>
    </div>
  </div>
  {% show_comments %}
{% endblock body %}

src/catalogs/templates/catalogs/author_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Form create author{% endblock title %}
{% block body %}
<body>
    <h1>Создать Автора</h1>
    {{ is_valid }}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success">Submit</button>

    </form>
</body>
{% endblock body %}

src/catalogs/templates/catalogs/author_list.html
{% extends 'base.html' %}
{% block title %}Author list{% endblock title %}
{% block body %}

<h1>Все авторы</h1>
<table class="table table-hover">
      <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Detail</th>
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for author in author_list %}
    <tr>
      <th scope="row"> {{ author.pk }}</th>
      <td><a href ="{% url 'author:author' author.pk %}">{{ author }}</a></td>
      <td><a href ="{% url 'author:author-update' author.pk %}" class='btn btn-success' >Update</a></td>
      <td><a href ="{% url 'author:author-delete' author.pk %}" class='btn btn-warning'>Delete</a></td>
    </tr>
    {% endfor %}
  </tbody>
  </table>
  <a href="{% url 'author:author-create' %}">Создать нового Автора</a> <br>
  <a href="{% url 'home' %}">На главную</a>

{% endblock body %}

src/catalogs/templates/catalogs/crew_page.html
{% extends 'base.html' %}
{% block title %}For crew{% endblock title %}
{% block body %}
<body>

    <h1>Добро пожаловать на страницу для персонала</h1>

    {{ user }} <br>



    <a href='/admin'> Админка </a>

    <ul>
        <li><a href ="{% url 'author:author-list' %}">Авторы</a></li>
        <li><a href ="{% url 'genre:genre-list' %}">Жанры</a></li>
        <li><a href ="{% url 'series:series-list' %}">Серии</a></li>
        <li><a href ="{% url 'publishinghouse:published-list' %}">Издательства</a></li>
        <li><a href ="{% url 'books:book-list-crew' %}">Книги</a></li>
    </ul>
    <a href="{% url 'books:book-create' %}">Создать Книгу</a> <br>
    <a href="{% url 'accounts:login' %}">залогиниться</a> <br>
    <a href="{% url 'accounts:logout' %}">свалить</a> <br>

    <a href="{% url 'accounts:register' %}">новый ЮЗЕР!</a> <br>

    <a href="{% url 'accounts:customer-list' %}">Все юзеры</a><br>


    <a href="{% url 'orders:list-order' %}">Все заказы</a><br>
    
    
</body>
{% endblock body %}

src/catalogs/templates/catalogs/genre_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete genre{% endblock title %}
{% block body %}
<body>
    <h1>Удалить Жанр???</h1>
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Submit</button>

    </form>
</body>
{% endblock body %}

src/catalogs/templates/catalogs/genre_detail.html
{% extends 'base.html' %}
{% load template_tags %}
{% block title %}Detail genre{% endblock title %}
{% block body %}
<div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Жанр</h5>
      <p class="card-text">    {{ genre }}<br>
        ID : {{ genre.pk }} <br>
        Description : {{ genre.genre_discription }} <br></p>
      <a href="{% url 'genre:genre-list' %}" class="btn btn-primary">К списку</a>
    </div>
  </div>
  {% show_comments %}
{% endblock body %}

src/catalogs/templates/catalogs/genre_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Form create genre{% endblock title %}
{% block body %}
<body>
    <h1>Создать Жанр</h1>
    {{ is_valid }}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success">Submit</button>

    </form>
</body>
{% endblock body %}

src/catalogs/templates/catalogs/genre_list.html
{% extends 'base.html' %}
{% block title %}Genre list{% endblock title %}
{% block body %}

    <h1>Все жанры</h1>
    <table class="table table-hover">
        <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Detail</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for genre in genre_list %}
      <tr>
        <th scope="row"> {{ genre.pk }}</th>
        <td><a href ="{% url 'genre:genre' genre.pk %}">{{ genre }}</a></td>
        <td><a href ="{% url 'genre:genre-update' genre.pk %}" class='btn btn-success' >Update</a></td>
        <td><a href ="{% url 'genre:genre-delete' genre.pk %}" class='btn btn-warning'>Delete</a></td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
    <a href="{% url 'genre:genre-create' %}">Создать новый Жанр</a> <br>
    <a href="{% url 'home' %}">На главную</a>

{% endblock body %}

src/catalogs/templates/catalogs/home.html
{% extends 'base.html' %}
{% block title %}Home page{% endblock title %}
{% block body %}
<body>
    <h1>Home page</h1>


    {{ user }} <br>



    <a href='/admin'> Админка </a>

    <ul>
        <li><a href ="{% url 'author:author-list' %}">Авторы</a></li>
        <li><a href ="{% url 'genre:genre-list' %}">Жанры</a></li>
        <li><a href ="{% url 'series:series-list' %}">Серии</a></li>
        <li><a href ="{% url 'publishinghouse:published-list' %}">Издательства</a></li>
        <li><a href ="{% url 'books:book-list' %}">Книги</a></li>
    </ul>
    <a href="{% url 'books:book-create' %}">Создать Книгу</a> <br>
    <a href="{% url 'accounts:login' %}">залогиниться</a> <br>
    <a href="{% url 'accounts:logout' %}">свалить</a> <br>
    <a href="{% url 'accounts:create-account' %}">Уточнить данные</a> <br>
    <a href="{% url 'accounts:register' %}">новый ЮЗЕР!</a> <br>
    
    
</body>
{% endblock body %}

src/catalogs/templates/catalogs/publishinghouse_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete publishing house{% endblock title %}
{% block body %}
<body>
    <h1>Удалить Издателя???</h1>
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Submit</button>

    </form>
</body>
{% endblock body %}

src/catalogs/templates/catalogs/publishinghouse_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Form create publishing house{% endblock title %}
{% block body %}
<body>
    <h1>Создать Издателя</h1>
    {{ is_valid }}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success">Submit</button>

    </form>
</body>
{% endblock body %}

src/catalogs/templates/catalogs/publishinghouse_list.html
{% extends 'base.html' %}
{% block title %}Publishing house list{% endblock title %}
{% block body %}

    <h1>Все издательсва</h1>
    <table class="table table-hover">
        <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Detail</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for published in object_list %}
      <tr>
        <th scope="row"> {{ published.pk }}</th>
        <td><a href ="{% url 'publishinghouse:published' published.pk %}">{{ published }}</a></td>
        <td><a href ="{% url 'publishinghouse:published-update' published.pk %}" class='btn btn-success' >Update</a></td>
        <td><a href ="{% url 'publishinghouse:published-delete' published.pk %}" class='btn btn-warning'>Delete</a></td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
    <a href="{% url 'publishinghouse:published-create' %}">Создать нового Издателя</a> <br>
    <a href="{% url 'home' %}">На главную</a>

{% endblock body %}

src/catalogs/templates/catalogs/series_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Form create series{% endblock title %}
{% block body %}
<body>
    <h1>Создать Серию</h1>
    {{ is_valid }}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success">Submit</button>

    </form>
</body>
{% endblock body %}

src/catalogs/templates/catalogs/series_list.html
{% extends 'base.html' %}
{% block title %}Series list{% endblock title %}
{% block body %}
<body>
    <h1>Все серии</h1>
    <table class="table table-hover">
        <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Detail</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for series in series_list %}
      <tr>
        <th scope="row"> {{ series.pk }}</th>
        <td><a href ="{% url 'series:series' series.pk %}">{{ series }}</a></td>
        <td><a href ="{% url 'series:series-update' series.pk %}" class='btn btn-success' >Update</a></td>
        <td><a href ="{% url 'series:series-delete' series.pk %}" class='btn btn-warning'>Delete</a></td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
    <a href="{% url 'series:series-create' %}">Создать новую Серию</a> <br>
    <a href="{% url 'home' %}">На главную</a>
    
{% endblock body %}