src/books/urls.py
from django.urls import path

from books import views as books_views

app_name = 'books'

urlpatterns = [

    path('book/<int:pk>/', books_views.BookDetailView.as_view(), name='book'),
    path('book-list/', books_views.BookListView.as_view(), name='book-list'),
    path('book-list-crew/', books_views.CrewBookListView.as_view(), name='book-list-crew'),
    path('home-books/', books_views.HomeBookListView.as_view(), name='home-books'),
    path('book_create/', books_views.BookCreateView.as_view(), name='book-create'),
    path('book_update/<int:pk>/', books_views.BookUpdateView.as_view(), name='book-update'),
    path('book_delete/<int:pk>/', books_views.BookDeleteView.as_view(), name='book-delete'),
]

src/carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart-edit/', views.CartView.as_view(),name='cart-edit'),
    path('cart-delete-good/<int:pk>', views.DeleteGoodInCartView.as_view(),name='cart-delete-good'),
    path('cart-update-good/', views.CartUpdate.as_view(),name='cart-update-good'),
    # path('author_update/<int:pk>/', cities_views.AuthorUpdateView.as_view(), name='author-update'),
    # path('author_delete/<int:pk>/', cities_views.AuthorDeleteView.as_view(), name='author-delete'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

from catalogs import views as catalogs_views
from books import views as books_views
#from books import urls, views as books_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('author/', include('catalogs.urls', namespace='author')),
    path('genre/', include('catalogs.urls', namespace='genre')),
    path('series/', include('catalogs.urls', namespace='series')),
    path('publishinghouse/', include('catalogs.urls', namespace='publishinghouse')),
    path('books/', include('books.urls', namespace='books')),
    path('accounts/', include('users.urls', namespace='accounts')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('comments/', include('comments.urls', namespace='comments')),

    path('', books_views.HomeBookListView.as_view(), name='home'),
    path('catalogs/', catalogs_views.CrewPage.as_view(), name='crew-page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/books/models.py
from django.db import models
from django.urls import reverse
from catalogs.models import Author, Genre, Series, PublishingHouse

# Create your models here.

class Book(models.Model):
    title_book = models.CharField(verbose_name="Название книги", max_length= 200)
    picture_book = models.ImageField(verbose_name="Картинка", upload_to = 'author/%Y/%m/%d/')
    book_price = models.IntegerField(verbose_name="Цена книги(BYN)")
    book_author = models.ManyToManyField(Author, related_name='authors') # должен быть справочник
    book_series = models.ForeignKey(Series, on_delete=models.PROTECT, related_name='series', blank=True, null=True) # должен быть справочник
    book_genre = models.ForeignKey(Genre, on_delete=models.PROTECT, related_name='genres') # должен быть справочник
    year_publishing = models.IntegerField(verbose_name= "Год издания")
    number_pages = models.IntegerField(verbose_name="Количество страниц")
    binding = models.CharField(verbose_name="Переплет",max_length= 100) # можно сделать справочик
    size = models.CharField(verbose_name="Формат", max_length= 100)
    ISBN = models.CharField(verbose_name="ISBN",max_length= 100)
    weight = models.IntegerField(verbose_name="Вес (гр)")
    age_restrictions = models.CharField(verbose_name="Возрастные ограничения",max_length=20)# можно сделать справочик
    publishing_house = models.ForeignKey(PublishingHouse, on_delete=models.PROTECT, related_name='publishing_houses') # должен быть справочник
    in_stock = models.IntegerField(verbose_name="Количество в наличии")
    available_to_order = models.BooleanField(verbose_name="Доступна к заказу", default=True)
    rating = models.IntegerField(verbose_name="Рейтинг (0-10)", blank=True, null=True)
    date_inclusion = models.DateTimeField(verbose_name="Дата внесения в каталог", auto_now_add=True, auto_now=False)
    date_change = models.DateTimeField(verbose_name="Дата последнего изменения карточки", auto_now_add=False, auto_now=True)

    def __str__(self) -> str:
        return f"{self.title_book}"

    def get_absolute_url(self):
        return reverse('books:book-list-crew')
    class Meta:
        verbose_name = "Книга"
        verbose_name_plural = "Книги"

src/books/forms.py
from django import forms
from . import models

class CreateBookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = '__all__'       

src/books/views.py
from django.core import paginator
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db.models import Q
from django.core.paginator import Paginator

from . import models
from . import forms

# Create your views here.

class BookDetailView(DetailView):
    model = models.Book

class BookListView(ListView):
    model = models.Book
    paginate_by = 3

    def get_queryset(self):
        qs = super().get_queryset()
        filter = self.request.GET.get('filter')
        q = self.request.GET.get('q')
        print(q)
        if q:
            # qs.filter(title_book__icontains=q)
            qs = qs.filter(Q(title_book__icontains=q) | Q(book_author__dim_1__icontains=q))
        return qs


class CrewBookListView(ListView):
    model = models.Book
    template_name = 'books/crewbook_list.html'
    paginate_by = 10
    def get_queryset(self):
        qs = super().get_queryset()
        filter = self.request.GET.get('filter')
        q = self.request.GET.get('q')
        print(q)
        if q:
            # qs.filter(title_book__icontains=q)
            qs = qs.filter(Q(title_book__icontains=q) | Q(book_author__dim_1__icontains=q))
        return qs        

class HomeBookListView(ListView):
    model = models.Book
    template_name = 'books/home_books.html'
    paginate_by = 6
    def get_queryset(self):
        qs = super().get_queryset()
        filter = self.request.GET.get('filter')
        q = self.request.GET.get('q')
        print(q)
        if q:
            qs = qs.filter(Q(title_book__icontains=q) | Q(book_author__dim_1__icontains=q))
        return qs     


class BookCreateView(PermissionRequiredMixin, CreateView):
    model = models.Book
    form_class = forms.CreateBookForm
    login_url = 'accounts:login'
    permission_required = 'books.add_book'

class BookUpdateView(PermissionRequiredMixin, UpdateView):
    model = models.Book
    form_class = forms.CreateBookForm
    login_url = 'accounts:login'
    permission_required = 'books.change_book'
    
class BookDeleteView(PermissionRequiredMixin, DeleteView):
    model = models.Book
    success_url = reverse_lazy('books:book-list-crew') 
    login_url = 'accounts:login'
    permission_required = 'books.delete_book'

src/books/templates/books/book_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete genre{% endblock title %}
{% block body %}
<body>
    <h1>Удалить Книгу???</h1>
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Submit</button>

    </form>
</body>
{% endblock body %}

src/books/templates/books/book_detail.html
{% extends 'base.html' %}
{% load template_tags %}
{% block title %}Detail book{% endblock title %}
{% block body %}
<div class="card" style="width: 18rem;">
  <img src="{{ book.picture_book.url }}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Книга</h5>
      <p class="card-text">    {{ book }}<br>

        <b>Автор</b> : 
        <ul>
          {% for dim_1 in book.book_author.all %}
          <li>{{ dim_1.dim_1 }}</li>
          {% endfor %}
        </ul>    
        <b>Серия</b> : {{ book.book_series }} <br>
        <b>Жанр</b> : {{ book.book_genre }} <br>
        <b>Год издания</b> : {{ book.year_publishing }} <br>
        <b>Количество страниц</b> : {{ book.number_pages }} <br>
        <b>Формат </b>: {{ book.size }} <br>
        <b>Переплет </b>: {{ book.binding }} <br>
        <b>ISBN</b> : {{ book.ISBN }} <br>
        <b>Издательство</b> : {{ book.publishing_house }} <br>
        <b>Возрастные ограничения</b> : {{ book.age_restrictions }} <br>
        <b>Вес (гр)</b> : {{ book.weight }} <br>
        <b>Количество в наличии (шт)</b>  : {{ book.in_stock }} <br>
        <b>Доступга к заказу</b> : {% if book.available_to_order %} 
          Есть на складе
        {% else %}
          Нет в наличии
        {% endif %}        <br>
        <b>Рейтинг</b> : {{ book.rating }} <br>
        <b>Стоимость за шт., BYN</b> : {{ book.book_price }} <br></p>
      <a href="{% url 'books:home-books' %}" class="btn btn-primary">На главную</a>
    </div>
  </div>
  {% show_comments %}
{% endblock body %}

src/books/templates/books/book_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Form create book{% endblock title %}
{% block body %}
<body>
    <h1>Создать Книгу</h1>
    {{ is_valid }}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success">Submit</button>

    </form>
</body>
{% endblock body %}

src/books/templates/books/book_list.html
{% extends 'base.html' %}
{% block title %}Book list{% endblock title %}
{% block body %}

    <h1>Все книги</h1>

    {% for book in book_list %}

    <div class="card" style="width: 18rem;">
      <img src="{{ book.picture_book.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Книга</h5>
          <p class="card-text">    {{ book }}<br>
            ID : {{ book.pk }} <br>
            <b>Автор</b> : 
            <ul>
              {% for dim_1 in book.book_author.all %}
              <li>{{ dim_1.dim_1 }}</li>
              {% endfor %}
            </ul>    
            <b>Серия</b> : {{ book.book_series }} <br>
            <b>Жанр</b> : {{ book.book_genre }} <br>
            <b>Год издания</b> : {{ book.year_publishing }} <br>
            <b>Количество страниц</b> : {{ book.number_pages }} <br>
            <b>Формат </b>: {{ book.size }} <br>
            <b>Переплет </b>: {{ book.tbinding }} <br>
            <b>ISBN</b> : {{ book.ISBN }} <br>
            <b>Издательство</b> : {{ book.publishing_house }} <br>
            <b>Возрастные ограничения</b> : {{ book.age_restrictions }} <br>
            <b>Вес (гр)</b> : {{ book.weight }} <br>
            <b>Количество в наличии (шт)</b>  : {{ book.in_stock }} <br>
            <b>Доступга к заказу</b> : {% if book.available_to_order %} 
              Есть на складе
            {% else %}
              Нет в наличии
            {% endif %}        <br>
            <b>Рейтинг</b> : {{ book.rating }} <br></p>
            <a href ="{% url 'carts:cart-edit' %}?book_id={{ book.pk }}" class='btn btn-primary'>Add to Cart</a>
        </div>
      </div>

    {% endfor %}


    <table class="table table-hover">
        <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Detail</th>
        {% if perm.books.change_book %}<th scope="col">Update</th>{% endif %}
        {% if perm.books.delete_book %}<th scope="col">Delete</th>{% endif %}
        <th scope="col">Add</th>
      </tr>
    </thead>
    <tbody>
      {% for book in book_list %}
      <tr>
        <th scope="row"> {{ book.pk }}</th>
        <td><a href ="{% url 'books:book' book.pk %}">{{ book }}</a></td>
        {% if perm.books.change_book %}<td><a href ="{% url 'books:book-update' book.pk %}" class='btn btn-success' >Update</a></td>{% endif %}
        {% if perm.books.delete_book %}<td><a href ="{% url 'books:book-delete' book.pk %}" class='btn btn-warning'>Delete</a></td>{% endif %}
        <td><a href ="{% url 'carts:cart-edit' %}?book_id={{ book.pk }}" class='btn btn-primary'>Add to Cart</a></td>
      </tr>
      {% endfor %}
    </tbody>
    </table>

    <!-- <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
  
          <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>
  
          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">next</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
      </span>
  </div> -->

  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}

      {% for page_num in paginator.page_range %}
      <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
      {% endif %}
    </ul>
  </nav>

    <a href="{% url 'books:book-create' %}">Создать новую книгу</a> <br>
    <a href="{% url 'home' %}">На главную</a>

{% endblock body %}

src/books/templates/books/book_list1.0.html
{% extends 'base.html' %}
{% block title %}Book list{% endblock title %}
{% block body %}

    <h1>Все книги</h1>
    <table class="table table-hover">
        <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Detail</th>
        {% if perm.books.change_book %}<th scope="col">Update</th>{% endif %}
        {% if perm.books.delete_book %}<th scope="col">Delete</th>{% endif %}
        <th scope="col">Add</th>
      </tr>
    </thead>
    <tbody>
      {% for book in book_list %}
      <tr>
        <th scope="row"> {{ book.pk }}</th>
        <td><a href ="{% url 'books:book' book.pk %}">{{ book }}</a></td>
        {% if perm.books.change_book %}<td><a href ="{% url 'books:book-update' book.pk %}" class='btn btn-success' >Update</a></td>{% endif %}
        {% if perm.books.delete_book %}<td><a href ="{% url 'books:book-delete' book.pk %}" class='btn btn-warning'>Delete</a></td>{% endif %}
        <td><a href ="{% url 'carts:cart-edit' %}?book_id={{ book.pk }}" class='btn btn-primary'>Add to Cart</a></td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
    <a href="{% url 'books:book-create' %}">Создать новую книгу</a> <br>
    <a href="{% url 'home' %}">На главную</a>

{% endblock body %}

src/books/templates/books/crewbook_list.html
{% extends 'base.html' %}
{% block title %}Book list{% endblock title %}
{% block body %}

    <h1>Все книги</h1>

    <h1>Оставь надежду!!!</h1>

    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

    <a href="{% url 'books:book-create' %}">Создать новую книгу</a><br>
    <a href="{% url 'home' %}">На главную</a><br>


    <table class="table table-hover">
        <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Detail</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
        <th scope="col">Add</th>
      </tr>
    </thead>
    <tbody>
      {% for book in book_list %}
      <tr>
        <th scope="row"> {{ book.pk }}</th>
        <td><a href ="{% url 'books:book' book.pk %}">{{ book }}</a></td>
        <td><a href ="{% url 'books:book-update' book.pk %}" class='btn btn-success' >Update</a></td>
        <td><a href ="{% url 'books:book-delete' book.pk %}" class='btn btn-warning'>Delete</a></td>
        <td><a href ="{% url 'carts:cart-edit' %}?book_id={{ book.pk }}" class='btn btn-primary'>Add to Cart</a></td>
      </tr>
      {% endfor %}
    </tbody>
    </table>


<br>
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}

      {% for page_num in paginator.page_range %}
      <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
      {% endif %}
    </ul>
  </nav>



{% endblock body %}

src/books/templates/books/home_books.html
{% extends 'base.html' %}
{% block title %}Home page{% endblock title %}
{% block body %}
<body>
    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
  
          {% for book in book_list %}
  
          <div class="col">
            <div class="card shadow-sm">
              <img src="{{ book.picture_book.url }}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Книга</h5>
                <p class="card-text"> <a href ="{% url 'books:book' book.pk %}">{{ book }}</a><br>
                  <b>Автор</b> : 
                  <ul>
                    {% for dim_1 in book.book_author.all %}
                    <li>{{ dim_1.dim_1 }}</li>
                    {% endfor %}
                  </ul>    
                  <b>Серия</b> : {{ book.book_series }} <br>
                  <b>Жанр</b> : {{ book.book_genre }} <br>
                  <b>Год издания</b> : {{ book.year_publishing }} <br>
                  <b>Количество страниц</b> : {{ book.number_pages }} <br>
                  <b>Формат </b>: {{ book.size }} <br>
                  <b>Переплет </b>: {{ book.binding }} <br>
                  <b>ISBN</b> : {{ book.ISBN }} <br>
                  <b>Издательство</b> : {{ book.publishing_house }} <br>
                  <b>Возрастные ограничения</b> : {{ book.age_restrictions }} <br>
                  <b>Вес (гр)</b> : {{ book.weight }} <br>
                  <b>Доступга к заказу</b> : {% if book.available_to_order %} 
                    Есть на складе
                  {% else %}
                    Нет в наличии
                  {% endif %}        <br>
                  <b>Стоимость за шт., BYN</b> : {{ book.book_price }} <br>
                  <b>Рейтинг</b> : {{ book.rating }} <br></p>
  
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a href ="{% url 'carts:cart-edit' %}?book_id={{ book.pk }}" class='btn btn-primary'>Add to Cart</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
  
          {% endfor %}
   
</body>
<p></p>
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% endif %}

    {% for page_num in paginator.page_range %}
    <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% endif %}
  </ul>
</nav>

{% endblock body %}