src/carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart-edit/', views.CartView.as_view(),name='cart-edit'),
    path('cart-delete-good/<int:pk>', views.DeleteGoodInCartView.as_view(),name='cart-delete-good'),
    path('cart-update-good/', views.CartUpdate.as_view(),name='cart-update-good'),
    # path('author_update/<int:pk>/', cities_views.AuthorUpdateView.as_view(), name='author-update'),
    # path('author_delete/<int:pk>/', cities_views.AuthorDeleteView.as_view(), name='author-delete'),
]

src/orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.CreateOrderView.as_view(),name='create-order'),
    path('list-order/', views.ListOrderView.as_view(),name='list-order'),
    path('deteil-order/<int:pk>/', views.DetailOrderView.as_view(),name='deteil-order'),
    path('update-order/<int:pk>/', views.UpdateOrderView.as_view(),name='update-order'),
    path('customer-list-order/', views.CustomerOrderListView.as_view(),name='customer-list-order'),
    path('customer-order-update/<int:pk>/', views.CustomerUpdateOrderView.as_view(), name='customer-order-update'),
    # path('author_delete/<int:pk>/', cities_views.AuthorDeleteView.as_view(), name='author-delete'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

from catalogs import views as catalogs_views
from books import views as books_views
#from books import urls, views as books_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('author/', include('catalogs.urls', namespace='author')),
    path('genre/', include('catalogs.urls', namespace='genre')),
    path('series/', include('catalogs.urls', namespace='series')),
    path('publishinghouse/', include('catalogs.urls', namespace='publishinghouse')),
    path('books/', include('books.urls', namespace='books')),
    path('accounts/', include('users.urls', namespace='accounts')),
    path('carts/', include('carts.urls', namespace='carts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('comments/', include('comments.urls', namespace='comments')),

    path('', books_views.HomeBookListView.as_view(), name='home'),
    path('catalogs/', catalogs_views.CrewPage.as_view(), name='crew-page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/models.py
from django.urls import reverse
from django.db import models
from django.db.models.fields.related import ForeignKey

from carts.models import Cart

# Create your models here.

class Order(models.Model):
    cart = ForeignKey(Cart, on_delete=models.PROTECT, verbose_name="Заказ")
    status_order = models.CharField(
        max_length=20,
        default='в обработке',
        choices=[
            ('в обработке', 'в обработке'),
            ('передан курьеру', 'передан курьеру'),
            ('выполнен', 'выполнен'),
            ('отменен', 'отменен')
        ]
    )
    contact_info = models.TextField(verbose_name='Контактная информация')
    created = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(verbose_name="Дата последнего изменения", auto_now_add=False, auto_now=True)
    canceled_order = models.CharField(max_length=40,verbose_name="Причина отмены заказа", blank=True, null=True,
        choices=[
            ('свяжитесь со мной', 'свяжитесь со мной'),
            ('отменить заказ', 'отменить заказ')
        ]
    )
    
    def get_absolute_url(self):
        return reverse('orders:list-order')

src/orders/forms.py
from django import forms
from django.db.models import fields
from . import models

class OrderCreateForm(forms.Form):
    contact_info = forms.CharField(label = 'Контактная инофрмация', required = True, widget=forms.TextInput)

class OrderUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields='__all__'

class CustomerOrderUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields= ('canceled_order',)

src/orders/views.py
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import FormView, UpdateView, DetailView
from django.contrib import messages
from django.views.generic.list import ListView

from orders import models
from . import forms
from .models import Order
# Create your views here.

class CreateOrderView(FormView):
    form_class =  forms.OrderCreateForm
    template_name = 'orders/create-order.html'
    def get_initial(self):
        if self.request.user.is_anonymous:
            return {}
        tel = self.request.user.customer.phone_number    
        return {'contact_info': tel}

    def form_valid(self, form):
        cart_id = self.request.session.get('cart_id')
        cart, created = models.Cart.objects.get_or_create(
                pk = cart_id,
                defaults={},
            )
        if created:
            return HttpResponseRedirect(reverse_lazy('carts:cart-edit'))
        ci = form.cleaned_data.get('contact_info')    
        order = models.Order.objects.create(
            cart = cart,
            contact_info = ci
        )
        del self.request.session['cart_id']
        messages.add_message(self.request, messages.INFO, f"Спасибо за закак {str(self.request.user)}. Ваш заказ принят!")
        return HttpResponseRedirect(reverse_lazy('home'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id')
        cart, created = models.Cart.objects.get_or_create(
                pk = cart_id,
                defaults={},
            )
        context['object'] = cart

        return context

class ListOrderView(ListView):
    model = models.Order

class DetailOrderView(DetailView):
    model = models.Order    

class UpdateOrderView(UpdateView):
    model = models.Order
    form_class = forms.OrderUpdateForm

class CustomerUpdateOrderView(UpdateView):
    model = models.Order
    form_class = forms.CustomerOrderUpdateForm  
    template_name = 'orders/customer-order-update.html'
    success_url = reverse_lazy('orders:customer-list-order')  

class CustomerOrderListView(ListView):
    model = Order
    template_name = 'orders/customer_user_list.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        carts = user.carts.all()
        orders = Order.objects.filter(cart__in=carts)
        cnt = {'object_list':orders}
        print(cnt)
        return cnt

src/orders/templates/orders/create-order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Book list{% endblock title %}
{% block body %}

<h1>Корзина</h1>

<form action="{% url 'carts:cart-update-good' %}" method="POST">

<table class="table">
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Книга</th>
          <th scope="col">Количество</th>
          <th scope="col">Цена</th>
          <th scope="col"></th>
        </tr>
      </thead>

    <tbody>
{% for good_in_cart in object.goods.all %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>Книга {{ good_in_cart.book }}</td>
      <td>
        <div class="mb-3">
            <input type="number" name="qauntityforgood_{{ good_in_cart.pk }}" min="1" step="1" class="form-control" value="{{ good_in_cart.quantity }}">
          </div>
        </td>
      <td>{{ good_in_cart.total_price }}</td>
      <td><a href="{% url 'carts:cart-delete-good' good_in_cart.pk %}" class='btn btn-sm btn-danger'> Удалить </a></td>
    </tr>

{% endfor %}

<tr>
    <td colspan="3">Total</td>
    <td>{{ object.total_price }}</td>
</tr>

</table>
{% csrf_token %}
<button type="submit" class="btn btn-warning" name="submit" value="save_cart">Сохранить корзину</button>
<button type="submit" class="btn btn-success" name="submit" value="create_order">Сохранить и заказать</button>
</form>

<h1>Информация о Вашем заказе</h1>
<form action="{% url 'orders:create-order' %}" method="post">
{{ form|crispy}}
{% csrf_token %}
<button type="submit" class="btn btn-success" >Заказать</button>
</form>
{% endblock body %}

src/orders/templates/orders/customer-order-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Form create order{% endblock title %}
{% block body %}
<body>
    <h1>Обновить заказ Покупателя</h1>
    {{ is_valid }}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success">Submit</button>

    </form>
</body>
{% endblock body %}

src/orders/templates/orders/customer_user_list.html
{% extends 'base.html' %}
{% block title %}Book list{% endblock title %}
{% block body %}

<h1>Детали заказа Покупателя</h1>


<table class="table table-hover">
    <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Detail</th>
    <th scope="col">Наименование книги и количество экземпляров</th>
    <th scope="col">Update</th>
    <th scope="col">Статус</th>
    <th scope="col">Дата оформления заказа</th>
    <th scope="col">Дата последнего изменения</th>

  </tr>
</thead>
<tbody>
  {% for order in object_list %}
  <tr>
    <th scope="row"> {{ order.pk }}</th>
    <td><a href ="{% url 'orders:deteil-order' order.pk %}">{{ order }}</a></td>
    <td>
      {% for book in order.cart.goods.all %}
      {{book.book}} <br>
      Цена штуки {{book.unit_price}} <br>
      Количество {{book.quantity}} <br><br>
      {% endfor %} 
    </td>
    <td><a href ="{% url 'orders:customer-order-update' order.pk %}" class='btn btn-success'>Отменить заказ?</a></td>
    <td>{{order.status_order}}</td>
    <td>{{order.created}}</td>
    <td>{{order.updated}}</td>

  </tr>
  {% endfor %}
</tbody>
</table>

<a href="{% url 'home' %}">На главную</a>


{% endblock body %}

src/orders/templates/orders/order_detail.html
{% extends 'base.html' %}
{% load template_tags %}
{% block title %}Detail order{% endblock title %}
{% block body %}
    <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">Детали заказа</h5>
      <p class="card-text">    {{ order }}<br>
        <b>ID</b> : {{ order.pk }} <br>
        <b>Корзина</b> : {{ order.cart.pk }}<br>
             

        <b>Книги</b> : 
        <ul>
          {% for book in order.cart.goods.all %}
          {{book.book}} <br>
          Цена штуки {{book.unit_price}} <br>
          Количество {{book.quantity}} <br><br>
          {% endfor %} 
        </ul>   

        <b>Статус заказа</b> : {{ order.status_order }} <br>
        <b>Контактные данные</b> : {{ order.contact_info }} <br>
        <b>Дата создания</b> : {{ order.created }} <br>
    </p>
      <a href="{% url 'orders:list-order' %}" class="btn btn-primary">К списку заказов</a>
    </div>
  </div>
  {% show_comments %}

  {{book.pk}}

{% endblock body %}

src/orders/templates/orders/order_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Form create series{% endblock title %}
{% block body %}
<body>
    <h1>Обновить заказ</h1>
    {{ is_valid }}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success">Submit</button>

    </form>
</body>
{% endblock body %}

src/orders/templates/orders/order_list.html
{% extends 'base.html' %}
{% block title %}Order list{% endblock title %}
{% block body %}

<h1>Все заказы</h1>

<table class="table table-hover">
      <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Detail</th>
      <th scope="col">Наименование книги и количество экземпляров</th>
      <th scope="col">Update</th>
      <th scope="col">Статус</th>
      <th scope="col">Дата оформления заказа</th>
      <th scope="col">Дата последнего изменения</th>
      <th scope="col">Статус отмены</th>

    </tr>
  </thead>
  <tbody>
    {% for order in object_list %}
    <tr>
      <th scope="row"> {{ order.pk }}</th>
      <td><a href ="{% url 'orders:deteil-order' order.pk %}">{{ order }}</a></td>
      <td>
        {% for book in order.cart.goods.all %}
        {{book.book}} <br>
        Цена штуки {{book.unit_price}} <br>
        Количество {{book.quantity}} <br><br>
        {% endfor %} 
      </td>
      <td><a href ="{% url 'orders:update-order' order.pk %}" class='btn btn-success'>Update</a></td>
      <td>{{order.status_order}}</td>
      <td>{{order.created}}</td>
      <td>{{order.updated}}</td>
      <td>{{order.canceled_order}}</td>

    </tr>
    {% endfor %}
  </tbody>
  </table>

  

  <a href="{% url 'home' %}">На главную</a>

{% endblock body %}